version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - .:/code
      - ./service-account.json:/code/app/service-account.json
    ports:
      - 8000:80
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_DB_NAME=fastapi_db_v2
      - GOOGLE_APPLICATION_CREDENTIALS=/code/app/service-account.json

    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: